# -----------------------------------------------------------------------------
# 网站设置
# -----------------------------------------------------------------------------

title: Blank # About Me
first_name: Li
middle_name:
last_name: Tang
contact_note: >
  You can also add a brief note indicating which of these methods is the best way to reach you.
description: >
  A simple, minimalist theme designed for academic use. Based on the design of [*folio*](https://github.com/bogoli/-folio).
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a>, with the <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
  Photos from <a href="https://unsplash.com" target="_blank">Unsplash</a>.
keywords: Jekyll, Jekyll-Theme, academic-website, portfolio-website
lang: en
icon: ⚛️
apple_touch_icon:

url: https://tang0103.github.io
baseurl:
last_updated: false
impressum_path:
back_to_top: true

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

repo_theme_light: default
repo_theme_dark: dark
protect_email: false

repo_trophies:
  enabled: false
  theme_light: flat
  theme_dark: gitdimmed

external_services:
  github_readme_stats_url: https://github-stats-extended.vercel.app
  github_profile_trophy_url: https://github-profile-trophy.vercel.app

# -----------------------------------------------------------------------------
# al-folio API (v1.x)
# -----------------------------------------------------------------------------

al_folio:
  api_version: 1
